### ISSUE TITLE
Monit is needed to test some of the entry points of the API

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#111]
@javizca : 

I have found during the weekend that some of the entry points are down. We should start monitoring them and receive and slack message when something is down. The following entry points should be tested: 

- https://www.ebi.ac.uk/pride/ws/archive/v2/facet/projects?dateGap=%2B1YEAR&facetPageSize=100

- https://www.ebi.ac.uk/pride/ws/archive/v2/spectra?page=0&pageSize=20

This is the minimum that should be checked.

**Comment by chakrabandla** [comment]
done
