### ISSUE TITLE
Implement Solr Cloud in Kubernetes 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#112]
@chakrabandla We need to check if we can implement a Kubernetes Cluster + Solr Cloud after we finish with the NFS mounting problems. This will give us the following benefits:

- We will have London / Hinxton support
- We will rely on System for Prod maintain. 
- We don't need to maintain anymore VMs 
- We can move to the cloud at anypoint.

**Comment by chakrabandla** [comment]
done
