### ISSUE TITLE
checksum validation in the submission pipeline

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-archive-pipelines#128]
Calculate checksum for individual file reported in the submission.px and validate them against checksum reported the the checksum.txt file submitted along with the submission.

**Comment by ypriverol** [comment]
@sureshhewabi can I close this issue?

**Comment by sureshhewabi** [comment]
> @sureshhewabi can I close this issue?

I did a pull request

**Comment by sureshhewabi** [comment]
https://bitbucket.org/proteomics-ebi/archive-submission-pipeline/pull-requests/30/dev/diff

**Comment by ypriverol** [comment]
Merged
