### ISSUE TITLE
Move of EBI search export to PRIDE post-submission pipelines

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#130]
We have been facing some issues with the export of PRIDE projects to EBI search. I recommend removing that pipeline from the submission pipeline into the post-submission pipeline.

**Comment by sureshhewabi** [comment]
@ypriverol Do you know what is the issue?

**Comment by ypriverol** [comment]
I think we should take this responsibility out of the submission pipeline because is synchronized with an external service. When @selvaebi finishes the Solr search problem we should look into this, also it will be less code to be move in the future.

**Comment by selvaebi** [comment]
hi, @ypriverol am done with the Solr search will look into this.

**Comment by ypriverol** [comment]
@selvaebi here is the job XML definition: 

https://bitbucket.org/proteomics-ebi/archive-submission-pipeline/src/master/src/main/resources/jobs/prider-ebeye-generation.xml

Here the tasklet: 

https://bitbucket.org/proteomics-ebi/archive-submission-pipeline/src/master/src/main/java/uk/ac/ebi/pride/tasklet/ebeye/GenerateEbeyeXmlTasklet.java

Please instead of connecting to Oracle for the generation use the MongoDB or SolrCoud.

**Comment by sureshhewabi** [comment]
There is a library to generate the XML file: https://github.com/PRIDE-Archive/archive-ebeye-xml
This has only one class `GenerateEBeyeXML` which does everything. It is better if we can put data into a model and generate it from that using `JAXB`. Also better to move XML generation code from the submission pipeline to this library to decompose the issue.

**Comment by sureshhewabi** [comment]
@selvaebi can we close this?

**Comment by selvaebi** [comment]
yes we can , but do we need to add this in post-submission too , right now its monthly cron job to run for all projects .
