### ISSUE TITLE
Big error in the indexing 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#143]
@selvaebi the last indexing in Solr broke the indexing of the keywords of the project. This is a big error and a major priority. 

<img width="1212" alt="Screen Shot 2020-05-24 at 15 46 34" src="https://user-images.githubusercontent.com/52113/82757095-1f2fa600-9dd6-11ea-8f65-c24ac2f68263.png">

**Comment by selvaebi** [comment]
Fixed replaced project_keywords_facet type to string and reindexed.
Pride archive API is now pointing to http://wp-p2m-30.ebi.ac.uk:8983/solr

**Comment by ypriverol** [comment]
Thanks !!!!

**Comment by javizca** [comment]
There must be still something that it is not working 100% well.
The query is the PRIDE website for SARS-CoV-2 and COVID-19 datasets does not retrieve any datasets right now.
https://www.ebi.ac.uk/pride/archive?filter=project_tags_facet%3D%3DSars-cov-2&sortDirection=DESC&page=0&pageSize=20

**Comment by selvaebi** [comment]
Ahhh sorry will fix it now. Its my bad

**Comment by ypriverol** [comment]
Solved
