### ISSUE TITLE
archive-repo should be updated to a micro-service

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-archive-pipelines#161]
archive-repo should be updated to a micro-service instead of a library. 
1. The main idea is to decouple this from revised-pipelines, so that we don't access to oracle db when there is no need 
2. it will be easier to migrate to postgres in future.

**Comment by ypriverol** [comment]
I think we should tackle this in one go: 

- Implement Oracle -> PostgreSQL data model
- Implement PostgreSQL as a micro-service. 
- replace all pipelines with the new PostgreSQL microservice 

@selvaebi with you @chakrabandla can take care of this. 

@chakrabandla what do you mean by micro-service?

**Comment by chakrabandla** [comment]
all interaction with oracle db should happen to Rest APIs ...
pipelines, pride API & private API should access those APIs to get or update data to Oracle.

In future we have to do this to mongo & solr access as well.. basically decouple everything

**Comment by ypriverol** [comment]
I like this approach but we have some issues that we probably need to tackle: 

- When multiple pipelines are running we will have a burden of memory in those APIs. 
- More code to maintain. Now for every provider-repo (mongo, solr, oracle), we will have three new libraries: 
     - the access-data api (current repo). This library will be used by the Restful API 
     - Restful API. 
     - Resultful client (this library will be used now by the pipelines, the PRIDE API, etc). 

While I love the approach, (no doubts) we really need to come with a project structure that allows us to easily maintain all this. It can be through Maven submodules, etc.

**Comment by chakrabandla** [comment]
>  When multiple pipelines are running we will have a burden of memory in those APIs.

We have to scale the APIs to handle any amount of load. We can deploy the oracle service in K8S cluster & scale dynamically (We can deploy in HX cluster only) 

> we will have three new libraries
No there will be only one i.e., archive-repo will have Restful APIs and eventually this will not be dependency in POM of any project anymore.
So, instead of adding it as a dependency & calling methods. We will have Restful clients accessing those APIs

Samething for other mongo & Solr

**Comment by ypriverol** [comment]
We will have two libraries then: 

- Current repo + API 
- Client

**Comment by chakrabandla** [comment]
clients are the repos accessing those APIs. So, in current scenario they are : 
1. pipelines (submission & revised)
2. pride APIs (both public & private)

no need of any new repo. only the way we access data changes.

It should be really easy to change the revised-pipelines & pride APIs to access data Restful way as mostly they are retrieving data from Oracle. 
Only submission pipeline will be major work.

**Comment by ypriverol** [comment]
The client is actually a library that can be used by every project to perform post/get from the API, with the same data structure. etc

**Comment by chakrabandla** [comment]
I am not sure if there will be any advantage of having such client. I think it will be just another unneeded dependency which we have to maintain.
for example, if the data structure changes, we have to update the client & the final consumer who is accessing that client.

**Comment by ypriverol** [comment]
If the idea is to have duplicated code. I'm also fine with that ;)

**Comment by chakrabandla** [comment]
ok..duplicate code is a good point :)

**Comment by chakrabandla** [comment]
for better performance, we can try reactive programming to develop the APIs ..
postgres looks to have good support for reactive jdbc.
https://github.com/r2dbc
