### ISSUE TITLE
List of projects failing

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-archive-pipelines#185]
**### **List of failing projects collected from Slack "pipeline-errors"****

**syncMongoProjectToSolrCloudJob**

1. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/spring_batch_solr_sync_add_one_project//spring_batch_solr_sync_add_one_project-PXD019394-202005261532.log  
2. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_solr_sync_add_one_project//spring_batch_solr_sync_add_one_project-PXD015462-202006180024.log

**mongoProjectProteinPeptideJobBean**

1. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/mongo_project_peptide_protein//mongo_project_peptide_protein--202005211354.log

**sanityCheckJobBean**

1. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/sanity_check/20200521_203853/./log/sanity_check//sanity_check--202005212054.log
2. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/sanity_check/20200521_203853/./log/sanity_check//sanity_check--202005212057.log
3. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/sanity_check/20200521_203853/./log/sanity_check//sanity_check--202005212105.log

**PrideUsersAAPSync**

1. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/pride-users-aap-sync//pride-users-aap-sync-202005211900.log
2. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/pride-users-aap-sync//pride-users-aap-sync-202005261530.log
3. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200717_131241/./log/pride-users-aap-sync//pride-users-aap-sync-202007171330.log

**syncOracleToMongoProjectsJob**

1. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019394-202005261532.log
2. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200521_133700/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019394-202005261604.log
3. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200526_213611/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019394-202005262139.log
4. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200526_215057/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD016613-202005271453.log
5. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200526_215057/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD013454-202005271452.log
6. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200526_215057/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD014754-202005271452.log
7. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200526_215057/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD018749-202006030231.log
8. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019645-202006290718.log
9. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019645-202006290740.log
10. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019645-202006291022.log
11. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD019645-202006291224.log
12. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD018749-202007020728.log
13. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD018749-202007091252.log
14. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD018749-202007101303.log
15. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD013454-202007101302.log
16. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD014754-202007101302.log
17. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/spring_batch_mongo_sync_accession//spring_batch_mongo_sync_accession-PXD020222-202007140750.log

**priderEbeyeXmlGenerationJob**

1. LOG: PXD002633-priderEbeyeXmlGenerationJob/60000m
2. LOG: PXD002633-priderEbeyeXmlGenerationJob/5000m
3. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200606_124414/./log/priderEbeyeXmlGenerationJob//PXD019119-priderEbeyeXmlGenerationJob
4. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200609_103841/20200609_103841/./log/priderEbeyeXmlGenerationJob//ebeye-allpub-priderEbeyeXmlGenerationJob-202006091112.log
5. LOG: /nfs/production3/pride/work/archive/gitlab-revised-archive-submission-pipeline/prod/20200612_152832/./log/priderEbeyeXmlGenerationJob//ebeye-allpub-priderEbeyeXmlGenerationJob-202007010000.log

**Comment by chakrabandla** [comment]
fixed :)
