### ISSUE TITLE
project_tags validation 

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-archive-pipelines#186]
1. we need to validate the project_tags in publication pipeline & curation tool pipeline against the [list in github](https://github.com/PRIDE-Utilities/pride-ontology/blob/master/pride-annotations/project-tags.csv): 

2. we need to release both updated publication job & updated curation tool at same time to avoid inconsistencies

3. A day before release, we should
a) stop publication jobs for a day
b) clean up & fix the existing projects tags (replace spaces with _  etc.,)
c) re-sync all updated tags to mongo & solr

**Comment by sureshhewabi** [comment]
@chakrabandla can we close this?
