### ISSUE TITLE
Convert Solr-repo to micro-service

### ISSUE THREAD

**Issue by chakrabandla** [PRIDE-Archive/pride-archive-pipelines#195]
Similar to what we are doing to Pride-repo, we need to convert Solr-repo to micro-service & deploy the API in Kubernetes.

We already have Solr-cloud in HX k8s cluster : https://pride-solr-hx-webadmin-11.wp-k8s.ebi.ac.uk/solr/#/

Just a summary of tasks:
1. Split the existing repo into API, commons & client
2. Deploy the API in k8s cluster : HX 
3. Replace existing pride-api & revised pipelines with client

**Comment by ypriverol** [comment]
@selvaebi @chakrabandla lets discuss this task on Thursday.
