### ISSUE TITLE
Transform the PRIDE XML terms to PSIMS when generating the PX file for ProteomeXchange

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#20]
We need to transform the PRIDE XML terms into PSI-MS terms when generating the proteomeXchange file in the publication job.

**Comment by sureshhewabi** [comment]
[PXT000001.xml.zip](https://github.com/PRIDE-Archive/pride-archive-pipelines/files/2795605/PXT000001.xml.zip)

**Comment by sureshhewabi** [comment]
Changes made to archive-px-xml-generator Library transform_pride_terms_to_psims branch

**Comment by ypriverol** [comment]
@sureshhewabi The validation gives us something like: 

>info=File has unexpected XSD 'proteomeXchange-1.3.0.xsd'. Cannot process this file. Sorry. At present, only proteomeXchange-1.4.0.xsd is permitted

>info=CV WARNING: MOD:00198 should be 'D-alanine (Ala)' instead of 'D-alanine'

info=The description for the submission is not sufficient. It must be at least 50 characters.

info=The title for the submission is not sufficient. It must be at least 30 characters.

Regards

**Comment by ypriverol** [comment]
@suresh we can use the API from proteomeCentral to validate the files, either by just trying submissions in `test mode` or using the `validateXML` method.

**Comment by sureshhewabi** [comment]
Fixed: 
PXD000002
PXD000019
PXD000020
PXD000024
PXD000034
PXD000057
PXD000060
PXD000068
PXD000122
PXD000130
PXD000137
PXD000140
PXD000146
PXD000184
PXD000199
PXD000200
PXD000204
PXD000207
PXD000285
PXD000286
PXD000305
PXD000315
PXD000353
PXD000425
PXD000453
PXD000481
PXD000482
PXD000519
PXD000527
PXD000542
PXD000544
PXD000555
PXD000598
PXD000607
PXD000610
PXD000613
PXD000616
PXD000628
PXD000633
PXD000634
PXD000641
PXD000803
PXD000884
PXD000889
PXD001155
PXD001321
PXD001557
PXD001779
PXD002019
PXD002060
PXD002219
PXD002329
PXD002338
PXD002341
PXD002343
PXD002348
PXD002382
PXD002477
PXD002535
PXD002860
PXD002929
PXD002962
PXD003017
PXD003026
PXD003069
PXD003160
PXD003263
PXD003383
PXD003393
PXD003394
PXD003537
PXD003855
PXD003939
PXD004029
PXD004258
PXD004539
PXD005002
PXD005077
PXD005078
PXD005331
PXD005385
PXD005504
PXD005631
PXD005912
PXD006541
PXD007512
PXD007823
PXD008652
PXD009086
PXD009128
PXD009201
PXD009290
PXD009562
PXD009765
PXD009937
PXD009946
PXD009990
PXD010493
PXD010499
PXD011617
PXD011767
PXD012172
PXD012316
PXD012357
PXD012373
PXD012504
PXD012523
PXD012528
PXD012559
PXD012703
