### ISSUE TITLE
SDRF Java Validator

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-archive-pipelines#201]
Create a java library which can validate SDRF files and output errors(if any) and integrate it to the submission tool

**Comment by ypriverol** [comment]
@sureshhewabi here the documentation: 

- Specification: https://github.com/bigbio/proteomics-metadata-standard/tree/master/sample-metadata
- Examples: https://github.com/bigbio/proteomics-metadata-standard/tree/master/annotated-projects
- Python library: https://github.com/bigbio/sdrf-pipelines/tree/master/sdrf_pipelines

We need a java library to read the file and apply a set of rules and guidelines to validate the file.

**Comment by sureshhewabi** [comment]
done
