### ISSUE TITLE
Error running runSubmission

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/pride-archive-pipelines#219]
Hello,

I have an issue running runSubmission in 1-20201124-56366. I tried yesterday and today and it keeps failing.
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=462726
The error is:
```
500 : [{"timestamp":1606303222345,"status":500,"error":"Internal Server Error","message":"","path":"/pride/archive/repo-api/submission/save"}]
org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 : [{"timestamp":1606303222345,"status":500,"error":"Internal Server Error","message":"","path":"/pride/archive/repo-api/submission/save"}]
        at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:100)
```

The validation was successful but not the submission.
The path to the dataset is /nfs/pride/prod/archive/1-20201124-56366
And you can find the submission error in:
/nfs/production3/pride/work/pipelines/gitlab-archive-submission-pipeline/20200905_143813/log/submission/1-20201124-56366-submission-202011251120.log

Regards,
David

**Comment by chakrabandla** [comment]
`org.postgresql.util.PSQLException: ERROR: value too long for type character varying(500)`

keywords field is huge

`"keywords": "Toxoplasma gondii, a single-celled protozoan parasite (phylum Apicomplexa) and remains the causative pathogen of one of the most wide-spread infectious diseases, toxoplasmosis. To continuously proliferate in warm-blooded animals, this parasite undergoes repeated cycles of invasion, division and induction of host cell rupture. Lactate, which is derived from cellular metabolic pathways, is widely considered not only an energy source in organisms but also a regulatory molecule that participates in gene activation. Lysine lactylation is a new type of protein posttranslational modification (PTM) that was recently associated with chromatin remodeling, but the lysine lactylation of histone and nonhistone proteins has not yet been studied in parasites. To examine the prevalence and function of lactylation in T. gondii parasites, we mapped the lactylation proteome of proliferating tachyzoite cells and found 1,964 lactylation sites on 955 proteins in the T. gondii RH strain. The lactylated proteins were distributed in multiple subcellular compartments and were closely related to a wide variety of biological processes, including mRNA splicing, the citrate cycle (TCA cycle), aminoacyl-tRNA biosynthesis, glyoxylate and dicarboxylate metabolism, glycolysis/gluconeogenesis, oxidative phosphorylation, RNA transport and the HIF-1 signaling pathway. Lysine lactation might regulate numerous cellular processes to aid the establishment of a hospitable environment that allows the survival, replication and dissemination of the parasite. These study offers the first data of the global lactylation proteome and provides a basis for further functional dissection of important proteins associated with T. gondii development and pathogenicity."`
