### ISSUE TITLE
Error found during dataset Validation

### ISSUE THREAD

**Issue by davco6** [PRIDE-Archive/pride-archive-pipelines#224]
Hello,

There is an error during the Validation of 1-20210128-55576, folder /nfs/pride/prod/archive/1-20210128-55576/, the error arises while reading project-citation:

Encountered an error executing step submissionCompletenessCheckStep in job validationJob
java.io.IOException: Error while reading project-citations file from - https://raw.githubusercontent.com/PRIDE-Utilities/pride-ontology/master/pride-annotations/project-tags.csv
        at uk.ac.ebi.pride.data.util.ValidateAnnotationFiles.getValidProjectTags(ValidateAnnotationFiles.java:37)
		

Thanks,
David

**Comment by chakrabandla** [comment]
should be fixed now.. please confirm & close this
