### ISSUE TITLE
We need to create a complete submission for testing performance

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#24]
The current pipeline for validation of complete submission takes a lot of time to perform the validations. I have made a lot of progress with the performance of mzIdentML validation. The problem we have now is that we don't know every time we perform a change in the ms-data-core-api if this really benefits the validation process. My suggestions are the following: 

Create a Big dataset and also and small:  
- Take an existing mzIdentML submission (we can talk to attila or deepte about this.). 
- Create a dump submission (submission test). 
- implement in the validation script a way to trace time. Looks like the jobs already have that mechanism: 

```
Started at Wed Jan 30 10:28:43 2019
Terminated at Wed Jan 30 10:29:13 2019
Results reported at Wed Jan 30 10:29:13 2019
```
We ned to create a folder for versioning of the pipeline for development. Meaining that we can compare versions.

**Comment by ypriverol** [comment]
Here a good dataset to perform the benchmark. http://wwwdev.ebi.ac.uk/pride/archive/projects/PXD002043

**Comment by ypriverol** [comment]
Here is the new version we should use for comparsion: ms-data-core-api:2.0.31-SNAPHOT

**Comment by sureshhewabi** [comment]
Files copied to /nfs/pride/drop/pride-drop-006/

- suresh_test_20190130_large_PX
- suresh_test_20190130_small_PX

Tickets:

- 1-20190130-1111 for large dataset
- 1-20190130-0000 for small dataset

Temporary/test Submission pipeline:
/nfs/pride/work/pipelines/archive-submission-pipeline/test/archive-submission-pipeline-20190130-1704

**Comment by sureshhewabi** [comment]
**validation-1-20190130-0000-RESUB2 - Small dataset validation:**

- Started at Thu Jan 31 11:40:56 2019
- Terminated at Thu Jan 31 20:16:12 2019
- Results reported at Thu Jan 31 20:16:12 2019

**Comment by sureshhewabi** [comment]
Small dataset validation in current submission pipeline
/nfs/pride/work/archive/filtering_px_submission_pipeline$ ./runValidation.sh -t 1-20190201-33333

**Comment by sureshhewabi** [comment]
this change is already in production.
