### ISSUE TITLE
Sync PX-XML files with ProteomeXchange

### ISSUE THREAD

**Issue by sureshhewabi** [PRIDE-Archive/pride-archive-pipelines#28]
There are some submissions that are private in ProteomeXchange but public in PRIDE archive.

**Comment by germa** [comment]
I think the reason could be that runSyncSubmission failed this morning, due to wrong file mappings in PXD007195, see more /nfs/pride/work/archive/submission-synchronizer/log/archive-submission-synchronizer-201903121600.log
Currently I am revalidating it (1-20190313-PXD007195-RESUB-0002). After submitting it, I'll try to run runSyncSubmission.sh again.

**Comment by sureshhewabi** [comment]
PXD013311 is not public on ProteomeXchange
PXD001346 is not public on ProteomeXchange
PXD014739 is not public on ProteomeXchange
PXD003870 is not public on ProteomeXchange
PXD003894 is not public on ProteomeXchange
PXD013288 is not public on ProteomeXchange
PXD013285 is not public on ProteomeXchange
PXD015943 is not public on ProteomeXchange
PXD006174 is not public on ProteomeXchange
PXD003905 is not public on ProteomeXchange
PXD003796 is not public on ProteomeXchange
PXD008610 is not public on ProteomeXchange
PXD009946 is not public on ProteomeXchange
PXD013178 is not public on ProteomeXchange
PXD009911 is not public on ProteomeXchange
PXD009978 is not public on ProteomeXchange
PXD013001 is not public on ProteomeXchange
PXD013067 is not public on ProteomeXchange
PXD007281 is not public on ProteomeXchange
PXD004002 is not public on ProteomeXchange
PXD006686 is not public on ProteomeXchange
PXD004094 is not public on ProteomeXchange
PXD000544 is not public on ProteomeXchange
PXD011226 is not public on ProteomeXchange
PXD013811 is not public on ProteomeXchange
PXD000520 is not public on ProteomeXchange
PXD012521 is not public on ProteomeXchange
PXD000353 is not public on ProteomeXchange
PXD011011 is not public on ProteomeXchange
PXD011035 is not public on ProteomeXchange
PXD012346 is not public on ProteomeXchange
PXD005231 is not public on ProteomeXchange
PXD007896 is not public on ProteomeXchange
PXD012418 is not public on ProteomeXchange
PXD013766 is not public on ProteomeXchange
PXD013591 is not public on ProteomeXchange
PXD013549 is not public on ProteomeXchange
PXD000228 is not public on ProteomeXchange
PXD006429 is not public on ProteomeXchange
PXD007716 is not public on ProteomeXchange
PXD005179 is not public on ProteomeXchange
PXD007782 is not public on ProteomeXchange
PXD014960 is not public on ProteomeXchange
PXD013619 is not public on ProteomeXchange
PXD013608 is not public on ProteomeXchange
PXD001630 is not public on ProteomeXchange
PXD012150 is not public on ProteomeXchange
PXD013452 is not public on ProteomeXchange
PXD007693 is not public on ProteomeXchange
PXD014833 is not public on ProteomeXchange
PXD014819 is not public on ProteomeXchange
PXD014802 is not public on ProteomeXchange
PXD009293 is not public on ProteomeXchange
PXD011605 is not public on ProteomeXchange
PXD011617 is not public on ProteomeXchange
PXD015163 is not public on ProteomeXchange
PXD012987 is not public on ProteomeXchange
PXD006926 is not public on ProteomeXchange
PXD016331 is not public on ProteomeXchange
PXD004332 is not public on ProteomeXchange
PXD015083 is not public on ProteomeXchange
PXD015078 is not public on ProteomeXchange
PXD011576 is not public on ProteomeXchange
PXD011581 is not public on ProteomeXchange
PXD010030 is not public on ProteomeXchange
PXD016209 is not public on ProteomeXchange
PXD006850 is not public on ProteomeXchange
PXD012716 is not public on ProteomeXchange
PXD012755 is not public on ProteomeXchange
PXD012762 is not public on ProteomeXchange
PXD005481 is not public on ProteomeXchange
PXD004182 is not public on ProteomeXchange
PXD012676 is not public on ProteomeXchange
PXD003539 is not public on ProteomeXchange
PXD003553 is not public on ProteomeXchange
PXD003501 is not public on ProteomeXchange
PXD014241 is not public on ProteomeXchange
PXD014235 is not public on ProteomeXchange
PXD010782 is not public on ProteomeXchange
PXD010780 is not public on ProteomeXchange
PXD003606 is not public on ProteomeXchange
PXD004762 is not public on ProteomeXchange
PXD004756 is not public on ProteomeXchange
PXD004744 is not public on ProteomeXchange
PXD011988 is not public on ProteomeXchange
PXD010666 is not public on ProteomeXchange
PXD010669 is not public on ProteomeXchange
PXD003310 is not public on ProteomeXchange
PXD016687 is not public on ProteomeXchange
PXD011835 is not public on ProteomeXchange
PXD010556 is not public on ProteomeXchange
PXD010557 is not public on ProteomeXchange
PXD010388 is not public on ProteomeXchange
PXD015240 is not public on ProteomeXchange
PXD011721 is not public on ProteomeXchange
PXD010414 is not public on ProteomeXchange
PXD010487 is not public on ProteomeXchange
