### ISSUE TITLE
We need to output to JSON files the PSMs, PEptides and Proteins 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#44]
When we run the Job PRIDEAnalyzeAssayJob we push all the data to MongoDB or S3. We can have the problem that if some data gets corrupted, then we will not be able to recover the data. We need to be able to pust all the data into a folder that we can recover then easyliy in case of disaster of the mongoDB or solr.

**Comment by sureshhewabi** [comment]
Each MongoDB records should be back up with the prefix of PXDID_AssayID_{protein, peptide, psm}.json

**Comment by ypriverol** [comment]
This has been implemented in a first approach.
