### ISSUE TITLE
Downtime in London March 

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#91]
Hi all: 

In March we will have downtime in London datacenter. I have been discussing with different teams how this will affect PRIDE. Here, what I got: 

- MongoDB (will be reachable, no changes for us) 
- FTP (still not clear what we are doing - Im trying to see a solution)
- The Kubernetes cluster will be down in London but the one in Hinxton will be fine. 
- The Solr Cloud VMs will be down. 

Taking that into account if we want to be live during this time we should do the following: 

- Move the remaining APIs to Kubernetes: 
  -  Submission API 
  - ProteomeXChange Web 
  - PX DOI WS 
  - Also, PRIDE public API should be move
  - Private API
- We need to move Solr Cloud to Kubernetes also because the search capabilities will be down on the web.

**Comment by javizca** [comment]
This work needs to get the highest priority, to ensure that we are fully functional by March

**Comment by javizca** [comment]
After further discussion with Yasset, we think it is better not to migrate the Solr Cloud (the searches in the web will not work for 3-4 days, we need to highlight this). Also we can live without the ProteomeXchange webpage

**Comment by javizca** [comment]
The APIs need to be migrated

**Comment by javizca** [comment]
And we need to understand the FTP issues (if any) before taking a decision

**Comment by ypriverol** [comment]
@javizca you need to be aware that the Solr Cloud is also used for the synchronization from Oracle to MongoDB. Then, if the Solr Cloud is not available, the sync should be stopped because if not will start breaking things. Correct me if I'm wrong @chakrabandla

**Comment by ypriverol** [comment]
> And we need to understand the FTP issues (if any) before taking a decision

I have told to Andrea and the PRIDE FTP will be accessible from Hinxton. Then, FTP will be fine.

**Comment by chakrabandla** [comment]
close this ?
