### ISSUE TITLE
Deploy the pipeline to compute the number of downloads per datasets

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-archive-pipelines#94]
In OmicsDI we implemented a pipeline that computes the number of downloads for each dataset. We should be able to deploy that pipeline in production in PRIDE and annotate for each dataset this number.

**Comment by ypriverol** [comment]
Please use this library, it should only be used with PRIDE provider. https://github.com/OmicsDI/ebi-logs-reader. You can contact @gdass in OmicsDI team

**Comment by sureshhewabi** [comment]
@ypriverol Where can I find the `ElasticSearch` parameters to run the code written in README?

- port
- machine
- username
- password

I ask Gauhari, he cannot remember.

**Comment by mindcrusher11** [comment]
I have shared it

**Comment by sureshhewabi** [comment]
@ypriverol This is an sample of data we get from the library you gave me:
![Screen Shot 2020-06-01 at 10 10 19 AM](https://user-images.githubusercontent.com/5387193/83399471-333c5e80-a3f9-11ea-9338-7e5e2de6f252.png)

We need to decide how we show data in web. That means if we are going to show number of downloads per dataset, if a person download only one file from the dataset, are we going to count it as a one download of that entire dataset?

For example, we do not care how many files they downloaded, we take it as a one download of the dataset.

**Comment by sureshhewabi** [comment]
Also, `ddi-ebi-logs` library does the calculations not only for PRIDE, but also for other resources.
![Screen Shot 2020-06-01 at 3 26 15 PM](https://user-images.githubusercontent.com/5387193/83428664-bf1aae80-a42a-11ea-83d8-4892840832b4.png)

Therefore, even if I calculate for a 1 day, it takes 2-3 hours to complete. I thought it is good to add a functionality so that it should do the calculations only for the given resource(PRIDE).

**Comment by ypriverol** [comment]
As I mentioned before web needs to wait. As far as I remember you can pass the database you want to query. in this case PRIDE only. We can discuss tomorrow.

**Comment by mindcrusher11** [comment]
We retrieve by database only.

It is there in pipeline I shared with you.

Thanks
Gaurhari

**Comment by sureshhewabi** [comment]
I am going to create a CV term under `File Properties` to report it as a CV term

<img width="465" alt="Screen Shot 2020-06-04 at 9 44 07 AM" src="https://user-images.githubusercontent.com/5387193/83735528-69bbe880-a648-11ea-8b4a-186d464565d7.png">

- CV Label: PRIDE
- Name: Number of Downloads
- Description: Number of downloads from PRIDE Aspera or FTP

**Comment by sureshhewabi** [comment]
Data is presented in the Additional attribute for each file:

![Screen Shot 2020-08-06 at 12 31 41 PM](https://user-images.githubusercontent.com/5387193/89527185-d5553a00-d7e0-11ea-925e-f61ad2083fdd.png)
